// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njhtyirsovqhdbztxqjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qaHR5aXJzb3ZxaGRienR4cWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1Nzk3NzUsImV4cCI6MjA4OTE1NTc3NX0.OA9PhgwG8Ysbo6tVErrQV8pD4ACgjrfGjgjqK7uj4Wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});